//create fornisseur
export const CREATE_CLIENT_REQUEST = 'CREATE_CLIENT_REQUEST'
export const CREATE_CLIENT_SUCCESS = 'CREATE_CLIENT_SUCCESS'
export const CREATE_CLIENT_FAIL = 'CREATE_CLIENT_FAIL'

//get all CLIENT
export const ALL_CLIENT_REQUEST = 'ALL_CLIENT_REQUEST'
export const ALL_CLIENT_SUCCESS = 'ALL_CLIENT_SUCCESS'
export const ALL_CLIENT_FAIL = 'ALL_CLIENT_FAIL'

//login CLIENT
export const LOGIN_CLIENT_REQUEST = 'LOGIN_CLIENT_REQUEST'
export const LOGIN_CLIENT_SUCCESS = 'LOGIN_CLIENT_SUCCESS'
export const LOGIN_CLIENT_FAIL = 'LOGIN_CLIENT_FAIL'

//GET MY SHIPS
export const MY_SHIPS_REQUEST = 'MY_SHIPS_REQUEST'
export const MY_SHIPS_SUCCESS = 'MY_SHIPS_SUCCESS'
export const MY_SHIPS_FAIL = 'MY_SHIPS_FAIL'

//GET SHIPS BY ID
export const GET_SHIPID_REQUEST = 'GET_SHIPID_REQUEST'
export const GET_SHIPID_SUCCESS = 'GET_SHIPID_SUCCESS'
export const GET_SHIPID_FAIL = 'GET_SHIPID_FAIL'

//update modal steps (second & third step) client part
export const UPDATE_MODAL_SHIP_CLIENT_FAIL = 'UPDATE_MODAL_SHIP_CLIENT_FAIL'
export const UPDATE_MODAL_SHIP_CLIENT_SUCCESS =
  'UPDATE_MODAL_SHIP_CLIENT_SUCCESS'
export const UPDATE_MODAL_SHIP_CLIENT_REQUEST =
  'UPDATE_MODAL_SHIP_CLIENT_REQUEST'
