export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const LOGOUT_SUCESS = 'LOGOUT_SUCESS'

//add ship stepes
export const CLIENT_ADDSHIP_REQUEST = 'CLIENT_ADDSHIP_REQUEST'
export const CLIENT_ADDSHIP_SUCESS = 'CLIENT_ADDSHIP_SUCESS'
export const CLIENT_ADDSHIP_FAIL = 'CLIENT_ADDSHIPFAIL'

export const CLIENT_FIRSTSHIP_REQUEST = 'CLIENT_FIRSTSHIP_REQUEST'
export const CLIENT_FIRSTSHIP_SUCESS = 'CLIENT_FIRSTSHIP_SUCESS'
export const CLIENT_FIRSTSHIP_FAIL = 'CLIENT_FIRSTSHIPFAIL'

export const CLIENT_SECONDSHIP_REQUEST = 'CLIENT_SECONDSHIP_REQUEST'
export const CLIENT_SECONDSHIP_SUCESS = 'CLIENT_SECONDSHIP_SUCESS'
export const CLIENT_SECONDSHIP_FAIL = 'CLIENT_SECONDSHIPFAIL'

//get numbers

//get number of ships
export const NBR_CLIENTSHIP_FAIL = 'NBR_CLIENTSHIP_FAIL'
export const NBR_CLIENTSHIP_SUCCESS = 'NBR_CLIENTSHIP_SUCCESS'
export const NBR_CLIENTSHIP_REQUEST = 'NBR_CLIENTSHIP_REQUEST'

export const SEND_NOTIFICATION = 'SEND_NOTIFICATION'
