export const ADD_UTILISATEUR_REQUEST = 'ADD_UTILISATEUR_REQUEST'
export const ADD_UTILISATEUR_SUCCESS = 'ADD_UTILISATEUR_SUCCESS'
export const ADD_UTILISATEUR_FAIL = 'ADD_UTILISATEUR_FAIL'

export const LIST_UTILISATEUR_REQUEST = 'LIST_UTILISATEUR_REQUEST'
export const LIST_UTILISATEUR_SUCCESS = 'LIST_UTILISATEUR_SUCCESS'
export const LIST_UTILISATEUR_FAIL = 'LIST_UTILISATEUR_FAIL'
